routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;




//Localization
Route::get('lang/{locale}',function ($locale){
   Session::put('locale',$locale);
   return redirect()->back();
})->name('lang');


Route::name('backend.')
    ->namespace('Backend')
    ->prefix('admin')
    ->middleware('role:admin')
    ->group(function () {

        Route::get('/', 'DashboardController@index')->name('dashboard');

        Route::get('/designation','DesignationController@index' )->name('designation.index');
        Route::post('/designation','DesignationController@store' )->name('designation.store');
        Route::post('/designation-destroy', 'DesignationController@destroy')->name('designation.destroy');




        //central committee
        Route::get('/central-committee','CentralCommitteeController@index' )->name('central-committee.list');
        Route::get('/central-committee-add', 'CentralCommitteeController@create')->name('central-committee.add');
        Route::get('/central-committee-edit/{id}', 'CentralCommitteeController@show')->name('central-committee.edit');
        Route::post('/central-committee-create', 'CentralCommitteeController@store')->name('central-committee.create');
        Route::post('/central-committee-update', 'CentralCommitteeController@update')->name('central-committee.update');
        Route::post('/central-committee-destroy', 'CentralCommitteeController@destroy')->name('central-committee.destroy');



        //district committee
        Route::get('/district-committee','DistrictCommitteeController@index' )->name('district-committee.list');
        Route::get('/district-committee-add', 'DistrictCommitteeController@create')->name('district-committee.add');
        Route::get('/district-committee-edit/{id}', 'DistrictCommitteeController@show')->name('district-committee.edit');
        Route::post('/district-committee-create', 'DistrictCommitteeController@store')->name('district-committee.create');
        Route::post('/district-committee-update', 'DistrictCommitteeController@update')->name('district-committee.update');
        Route::post('/district-committee-destroy', 'DistrictCommitteeController@destroy')->name('district-committee.destroy');


        //district committee
        Route::get('/department-committee','DepartmentCommitteeController@index' )->name('department-committee.list');
        Route::get('/department-committee-add', 'DepartmentCommitteeController@create')->name('department-committee.add');
        Route::get('/department-committee-edit/{id}', 'DepartmentCommitteeController@show')->name('department-committee.edit');
        Route::post('/department-committee-create', 'DepartmentCommitteeController@store')->name('department-committee.create');
        Route::post('/department-committee-update', 'DepartmentCommitteeController@update')->name('department-committee.update');
        Route::post('/department-committee-destroy', 'DepartmentCommitteeController@destroy')->name('department-committee.destroy');



        Route::get('/users', 'DashboardController@userList')->name('user.list');
        Route::get('/users/{id}', 'DashboardController@userShow')->name('user.show');

        //Genereal member
        Route::get('/general-member','GeneralMemberController@index' )->name('general-member.list');
        Route::get('/general-member-edit/{id}', 'GeneralMemberController@show')->name('general-member.edit');
        Route::post('/general-member-create', 'GeneralMemberController@store')->name('general-member.create');
        Route::post('/general-member-update', 'GeneralMemberController@update')->name('general-member.update');
        Route::post('/general-member-destroy', 'GeneralMemberController@destroy')->name('general-member.destroy');


        Route::get('/general-member-successful/{id}', 'GeneralMemberController@successful')->name('general-member.successful');
        Route::get('/general-member-canceled/{id}', 'GeneralMemberController@canceled')->name('general-member.canceled');

        //  notice route
        Route::get('/notice', 'NoticeController@index')->name('notice.list');
        Route::get('/notice-add', 'NoticeController@create')->name('notice.add');
        Route::get('/notice-edit/{id}', 'NoticeController@show')->name('notice.edit');
        // for slug generation
        Route::get('/check_slug', 'NoticeController@check_slug')->name('notice.slug');
        // notice create
        Route::post('/notice-create', 'NoticeController@store')->name('notice.create');
        Route::post('/notice-update', 'NoticeController@update')->name('notice.update');
        Route::post('/notice-destroy', 'NoticeController@destroy')->name('notice.destroy');

    });



Route::name('frontend.')
    ->namespace('Frontend')
    ->group(function (){

        Route::get('/','IndexController@index' )->name('index');

       // Route::get('/general-form', 'CentralCommitteController@index')->name('generalMember.form');
      //  Route::post('/central-form', 'GeneralMemberController@store')->name('generalMember.store');
        Route::get('/central-committee', 'CommitteeController@centralCommittee')->name('centralCommittee.list');

        Route::get('/district-committee', 'CommitteeController@districtCommittee')->name('districtCommittee.list');
        Route::get('/district-committee/{dist}', 'CommitteeController@districtShow')->name('districtCommittee.show');

        Route::get('/department-committee/{dpt}', 'CommitteeController@departmentShow')->name('departmentCommittee.show');


        Route::get('/general-form', 'GeneralMemberController@index')->name('generalMember.form');
        Route::post('/general-form', 'GeneralMemberController@store')->name('generalMember.store');


        Route::get('/dashboard', 'IndexController@dashboard')->name('dashboard');

//        Route::get('/id', 'GeneralMemberController@pdf2')->name('id');

        Route::get('/notices', 'NoticesController@index')->name('notice.list');
        Route::get('/notices/{id}', 'NoticesController@show')->name('notice.show');

        Route::get('/pdf/{id}', 'GeneralMemberController@generatePdf')->name('pdf');

    });

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/frontend/theme/includes/footer.blade.php
<div class="footer mt-5 ">
    <div class="text-center text-black small-text">
        {{ __('footer.copy') }} ©<span> {{ __('footer.copyright') }} </span> <br>
        {{ __('footer.support') }}: <span> {{ __('footer.company') }}</span>
    </div>
</div>

resources/views/frontend/theme/includes/head.blade.php
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="76x76" href=" {{ asset('frontend/img/apple-icon.png') }} ">
    <link rel="icon" type="image/png" href="{{ asset('frontend/img/favicon.png') }}  ">
    <title>
        @yield('title') • BDPP • Bangabandhu Diploma Engineer Porishod
    </title>
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800" rel="stylesheet" />
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <!-- Nucleo Icons -->
    <link href="{{ asset('frontend/css/nucleo-icons.css') }} " rel="stylesheet" />
    <!-- CSS Files -->
    <link href="{{ asset('frontend/css/blk-design-system.css?v=1.0.0') }}" rel="stylesheet" />

    <!-- custom css -->
    <link rel="stylesheet" type="text/css" href="{{ asset('frontend/css/stylesheet.css') }}  ">

    <style>
        .dropbtn {
            background-color: #4CAF50;
            color: white;
            padding: 16px;
            font-size: 16px;
            border: none;
        }

        .dropdown {
            position: relative;
            display: inline-block;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #D6D275;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

        .dropdown-content a {
            color: black !important;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
            font-size: 1.2em;
        }

        .dropdown-content a:hover {background-color: #D6D275;}

        .dropdown:hover .dropdown-content {display: block;}

        .dropdown:hover .dropbtn {background-color: #3e8e41;}
    </style>
    @yield('css')

</head>

resources/views/frontend/theme/includes/navbar.blade.php
<nav class="navbar-default bg-menu-image" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <img class="img-responsive" src="{{ asset('frontend/img/bango.png') }} ">
        </div>
    </div>
</nav>

<nav class="navbar navbar-expand-lg bg-menu nav-shadow">
    <div class="container ">
        <div class="navbar-translate text-black">
            <a class="navbar-brand" href="../bdpp/" data-placement="bottom" >
                <span> </span>
            </a>
            <button class="navbar-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse justify-content-end bg-menu text-black" id="navigation">
            <div class="navbar-collapse-header">
                <div class="row">
                    <div class="col-6 collapse-brand">
                    </div>
                    <div class="col-12 collapse-close text-right">
                        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                            <i class="tim-icons icon-simple-remove"></i>
                        </button>
                    </div>
                </div>
            </div>
            <ul class="navbar-nav m-auto">

                <li class="nav-item active">
                    <a class="nav-link " href="{{ route('frontend.index') }}">
                        {{ __('nav.home') }}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="{{ route('frontend.notice.list') }}">
                        {{ __('nav.notice') }}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="{{ route('frontend.centralCommittee.list') }}">
                        {{ __('nav.central') }}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('frontend.districtCommittee.list') }}">
                        {{ __('nav.district') }}
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link " >
                        {{ __('nav.department') }}
                    </a>
                    <div class="dropdown-content">
                        <a href="{{ route('frontend.departmentCommittee.show',['id' => 'সরকারি']) }}"> {{ __('nav.government') }}</a>
                        <a href="{{ route('frontend.departmentCommittee.show',['id' => 'বেসরকারী']) }}"> {{ __('nav.non-government') }}</a>
                        <a href="{{ route('frontend.departmentCommittee.show',['id' => 'অন্যান্য']) }}"> {{ __('nav.other') }}</a>
                    </div>
                </li>

                <li class="nav-item">
                    <a class="nav-link " href="{{ route('frontend.generalMember.form') }}">
                        {{ __('nav.form') }}
                    </a>
                </li>


                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('nav.login') }}</a>
                    </li>
                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('nav.register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item">
                        <a class="nav-link " href="{{ route('frontend.dashboard') }}">
                            Dashboard
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " href="{{ route('logout') }}"
                           onclick="event.preventDefault();
document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </li>

                @endguest

                <li class="nav-item">
                    <a class="nav-link" href="{{ route('lang', ['locale' => __('nav.locale') ] ) }}">
                        {{ __('nav.lang') }}
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/frontend/theme/includes/script.blade.php
<!--   Core JS Files   -->
<script src="{{ asset('frontend/js/core/jquery.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('frontend/js/core/popper.min.js"') }}" type="text/javascript"></script>
<script src="{{ asset('frontend/js/core/bootstrap.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('frontend/js/plugins/perfect-scrollbar.jquery.min.js') }}"></script>
<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<script src="{{ asset('frontend/js/plugins/bootstrap-switch.js') }}"></script>
<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
<script src="{{ asset('frontend/js/plugins/nouislider.min.js') }}" type="text/javascript"></script>
<!-- Chart JS -->
<script src="{{ asset('frontend/js/plugins/chartjs.min.js') }}"></script>
<!--  Plugin for the DatePicker, full documentation here: https://github.com/uxsolutions/bootstrap-datepicker -->
<script src="{{ asset('frontend/js/plugins/moment.min.js') }}./assets/js/plugins/moment.min.js"></script>
<script src="{{ asset('frontend/js/plugins/bootstrap-datetimepicker.jss') }}" type="text/javascript"></script>
<!-- Black Dashboard DEMO methods, don't include it in your project! -->
{{--<script src="{{ asset('frontend/demo/demo.js') }}./assets/demo/demo.js"></script>--}}

<!-- Control Center for Black UI Kit: parallax effects, scripts for the example pages etc -->
<script src="{{ asset('frontend/js/blk-design-system.min.js?v=1.0.0') }}" type="text/javascript"></script>


<script>
    $('.carousel').carousel();
    $(document).ready(function() {
        blackKit.initDatePicker();
        blackKit.initSliders();
    });

    function scrollToDownload() {

        if ($('.section-download').length != 0) {
            $("html, body").animate({
                scrollTop: $('.section-download').offset().top
            }, 1000);
        }
    }
</script>