routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;




//Localization
Route::get('lang/{locale}',function ($locale){
   Session::put('locale',$locale);
   return redirect()->back();
})->name('lang');


Route::name('backend.')
    ->namespace('Backend')
    ->prefix('admin')
    ->middleware('role:admin')
    ->group(function () {

        Route::get('/', 'DashboardController@index')->name('dashboard');

        Route::get('/designation','DesignationController@index' )->name('designation.index');
        Route::post('/designation','DesignationController@store' )->name('designation.store');
        Route::post('/designation-destroy', 'DesignationController@destroy')->name('designation.destroy');




        //central committee
        Route::get('/central-committee','CentralCommitteeController@index' )->name('central-committee.list');
        Route::get('/central-committee-add', 'CentralCommitteeController@create')->name('central-committee.add');
        Route::get('/central-committee-edit/{id}', 'CentralCommitteeController@show')->name('central-committee.edit');
        Route::post('/central-committee-create', 'CentralCommitteeController@store')->name('central-committee.create');
        Route::post('/central-committee-update', 'CentralCommitteeController@update')->name('central-committee.update');
        Route::post('/central-committee-destroy', 'CentralCommitteeController@destroy')->name('central-committee.destroy');



        //district committee
        Route::get('/district-committee','DistrictCommitteeController@index' )->name('district-committee.list');
        Route::get('/district-committee-add', 'DistrictCommitteeController@create')->name('district-committee.add');
        Route::get('/district-committee-edit/{id}', 'DistrictCommitteeController@show')->name('district-committee.edit');
        Route::post('/district-committee-create', 'DistrictCommitteeController@store')->name('district-committee.create');
        Route::post('/district-committee-update', 'DistrictCommitteeController@update')->name('district-committee.update');
        Route::post('/district-committee-destroy', 'DistrictCommitteeController@destroy')->name('district-committee.destroy');


        //district committee
        Route::get('/department-committee','DepartmentCommitteeController@index' )->name('department-committee.list');
        Route::get('/department-committee-add', 'DepartmentCommitteeController@create')->name('department-committee.add');
        Route::get('/department-committee-edit/{id}', 'DepartmentCommitteeController@show')->name('department-committee.edit');
        Route::post('/department-committee-create', 'DepartmentCommitteeController@store')->name('department-committee.create');
        Route::post('/department-committee-update', 'DepartmentCommitteeController@update')->name('department-committee.update');
        Route::post('/department-committee-destroy', 'DepartmentCommitteeController@destroy')->name('department-committee.destroy');



        Route::get('/users', 'DashboardController@userList')->name('user.list');
        Route::get('/users/{id}', 'DashboardController@userShow')->name('user.show');

        //Genereal member
        Route::get('/general-member','GeneralMemberController@index' )->name('general-member.list');
        Route::get('/general-member-edit/{id}', 'GeneralMemberController@show')->name('general-member.edit');
        Route::post('/general-member-create', 'GeneralMemberController@store')->name('general-member.create');
        Route::post('/general-member-update', 'GeneralMemberController@update')->name('general-member.update');
        Route::post('/general-member-destroy', 'GeneralMemberController@destroy')->name('general-member.destroy');


        Route::get('/general-member-successful/{id}', 'GeneralMemberController@successful')->name('general-member.successful');
        Route::get('/general-member-canceled/{id}', 'GeneralMemberController@canceled')->name('general-member.canceled');

        //  notice route
        Route::get('/notice', 'NoticeController@index')->name('notice.list');
        Route::get('/notice-add', 'NoticeController@create')->name('notice.add');
        Route::get('/notice-edit/{id}', 'NoticeController@show')->name('notice.edit');
        // for slug generation
        Route::get('/check_slug', 'NoticeController@check_slug')->name('notice.slug');
        // notice create
        Route::post('/notice-create', 'NoticeController@store')->name('notice.create');
        Route::post('/notice-update', 'NoticeController@update')->name('notice.update');
        Route::post('/notice-destroy', 'NoticeController@destroy')->name('notice.destroy');

    });



Route::name('frontend.')
    ->namespace('Frontend')
    ->group(function (){

        Route::get('/','IndexController@index' )->name('index');

       // Route::get('/general-form', 'CentralCommitteController@index')->name('generalMember.form');
      //  Route::post('/central-form', 'GeneralMemberController@store')->name('generalMember.store');
        Route::get('/central-committee', 'CommitteeController@centralCommittee')->name('centralCommittee.list');

        Route::get('/district-committee', 'CommitteeController@districtCommittee')->name('districtCommittee.list');
        Route::get('/district-committee/{dist}', 'CommitteeController@districtShow')->name('districtCommittee.show');

        Route::get('/department-committee/{dpt}', 'CommitteeController@departmentShow')->name('departmentCommittee.show');


        Route::get('/general-form', 'GeneralMemberController@index')->name('generalMember.form');
        Route::post('/general-form', 'GeneralMemberController@store')->name('generalMember.store');


        Route::get('/dashboard', 'IndexController@dashboard')->name('dashboard');

//        Route::get('/id', 'GeneralMemberController@pdf2')->name('id');

        Route::get('/notices', 'NoticesController@index')->name('notice.list');
        Route::get('/notices/{id}', 'NoticesController@show')->name('notice.show');

        Route::get('/pdf/{id}', 'GeneralMemberController@generatePdf')->name('pdf');

    });

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/backend/pages/district/edit.blade.php
@extends('backend.layouts.app')
@section('title' , 'District Committee Edit')

@section('content')

        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Update district Committee info
                <small>{{ $district->name }} </small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ route('backend.dashboard') }}"><i class="fa fa-dashboard"></i> Admin</a></li>
                <li><a href=" {{ route('backend.notice.list') }}"><i class="fa fa-shopping-cart"></i> District Committee</a></li>
                <li class="active">Edit District Committee</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content container-fluid">

            <div class="product">
                <!-- Horizontal Form -->
                <div class="box box-info">
                    <!-- form start -->
                    <form accept-charset="UTF-8" class="form-horizontal" action="{{ route('backend.district-committee.update') }}" method="post"
                          enctype="multipart/form-data">
                        @csrf
                        <input type="hidden" class="form-control"  name="id" value="{{ $district->id }}" >
                        <div class="box-body">

                            <div class="form-group">
                                <label for="inputTitle" class="col-sm-2 control-label">Name</label>

                                <div class="col-sm-10">
                                    <input type="text" value=" {{ $district->name }} " class="form-control" id="inputTitle" name="districtName" placeholder="Name" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputTitle" class="col-sm-2 control-label">District</label>

                                <div class="col-sm-10">
                                    <label>
                                        <select class="form-control" name="district"  id="dis" required>
                                            <option value="" disabled selected>নির্বাচন করুন</option>
                                            <optgroup label="ঢাকা">
                                                <option value="ঢাকা">ঢাকা</option><option value="ফরিদপুর">ফরিদপুর</option>
                                                <option value="গাজীপুর">গাজীপুর</option><option value="গোপালগঞ্জ">গোপালগঞ্জ</option><option value="জামালপুর">জামালপুর</option>
                                                <option value="কিশোরগঞ্জ">কিশোরগঞ্জ</option><option value="মাদারীপুর">মাদারীপুর</option><option value="মানিকগঞ্জ">মানিকগঞ্জ</option>
                                                <option value="মুন্সীগঞ্জ">মুন্সীগঞ্জ</option><option value="ময়মনসিংহ">ময়মনসিংহ</option><option value="নারায়ণগঞ্জ">নারায়ণগঞ্জ</option>
                                                <option value="নরসিংদী">নরসিংদী</option><option value="নেত্রকোনা">নেত্রকোনা</option><option value="রাজবাড়ী">রাজবাড়ী</option>
                                                <option value="শরিয়তপুর">শরিয়তপুর</option><option value="শেরপুর">শেরপুর</option><option value="টাঙ্গাইল">টাঙ্গাইল</option>
                                            </optgroup>
                                            <optgroup label="বরিশাল">
                                                <option value="বরগুনা">বরগুনা</option><option value="বরিশাল">বরিশাল</option>
                                                <option value="ভোলা">ভোলা</option><option value="ঝালকাঠী">ঝালকাঠী</option><option value="পটুয়াখালী">পটুয়াখালী</option>
                                                <option value="পিরোজপুর">পিরোজপুর</option> </optgroup>
                                            <optgroup label="চট্টগ্রাম">
                                                <option value="বান্দরবান">বান্দরবান</option><option value="ব্রাহ্মণবাড়িয়া">ব্রাহ্মণবাড়িয়া</option><option value="চাঁদপুর">চাঁদপুর</option>
                                                <option value="চট্টগ্রাম">চট্টগ্রাম</option><option value="কুমিল্লা">কুমিল্লা</option><option value="কক্সবাজার">কক্সবাজার</option>
                                                <option value="ফেনী">ফেনী</option><option value="খাগড়াছড়ি">খাগড়াছড়ি</option><option value="লক্ষ্মীপুর">লক্ষ্মীপুর</option>
                                                <option value="নোয়াখালী">নোয়াখালী</option><option value="রাঙ্গামাটি">রাঙ্গামাটি</option>
                                            </optgroup>                        <optgroup label="খুলনা">
                                                <option value="বাগেরহাট">বাগেরহাট</option><option value="চুয়াডাঙ্গা">চুয়াডাঙ্গা</option><option value="যশোর">যশোর</option>
                                                <option value="ঝিনাইদহ">ঝিনাইদহ</option><option value="খুলনা">খুলনা</option><option value="কুষ্টিয়া">কুষ্টিয়া</option>
                                                <option value="মাগুরা">মাগুরা</option><option value="মেহেরপুর">মেহেরপুর</option><option value="নড়াইল">নড়াইল</option>
                                                <option value="সাতক্ষীরা">সাতক্ষীরা</option> </optgroup>
                                            <optgroup label="রাজশাহী">
                                                <option value="বগুড়া">বগুড়া</option><option value="জয়পুরহাট">জয়পুরহাট</option><option value="নওগাঁ">নওগাঁ</option>
                                                <option value="নাটোর">নাটোর</option><option value="চাঁপাইনবাবগঞ্জ">চাঁপাইনবাবগঞ্জ</option><option value="পাবনা">পাবনা</option>
                                                <option value="রাজশাহী">রাজশাহী</option><option value="সিরাজগঞ্জ">সিরাজগঞ্জ</option>
                                            </optgroup>                        <optgroup label="সিলেট">
                                                <option value="হবিগঞ্জ">হবিগঞ্জ</option><option value="মৌলভীবাজার">মৌলভীবাজার</option><option value="সুনামগঞ্জ">সুনামগঞ্জ</option>
                                                <option value="সিলেট">সিলেট</option> </optgroup>
                                            <optgroup label="রংপুর">
                                                <option value="দিনাজপুর">দিনাজপুর</option><option value="গাইবান্ধা">গাইবান্ধা</option><option value="কুড়িগ্রাম">কুড়িগ্রাম</option>
                                                <option value="লালমনিরহাট">লালমনিরহাট</option><option value="নীলফামারী">নীলফামারী</option><option value="পঞ্চগড়">পঞ্চগড়</option>
                                                <option value="রংপুর">রংপুর</option><option value="ঠাকুরগাঁও">ঠাকুরগাঁও</option> </optgroup>

                                        </select>
                                    </label>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputTitle" class="col-sm-2 control-label">Designation</label>

                                <div class="col-sm-10">



                                    <select  name="districtDesignation" class="form-control" id="desig" required >
                                        @foreach($designations as $d)
                                            <option value="{{ $d['id'] }}">{{ $d['title'] }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputTitle" class="col-sm-2 control-label">Details</label>

                                <div class="col-sm-10">
                                    <input type="text"  value=" {{ $district->details }} " class="form-control" id="inputTitle" name="districtDetails" placeholder="Details" >
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputTitle" class="col-sm-2 control-label">Email</label>

                                <div class="col-sm-10">
                                    <input type="email"  value=" {{ $district->email }} " class="form-control" id="inputTitle" name="districtEmail" placeholder="Email" >
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputTitle" class="col-sm-2 control-label">Mobile</label>

                                <div class="col-sm-10">
                                    <input type="text"  value=" {{ $district->mobile }} " class="form-control" id="inputTitle" name="districtMobile" placeholder="Mobile" required>
                                </div>
                            </div>


                            <div class="form-group">
                                <label for="inputTitle" class="col-sm-2 control-label">Photo</label>

                                <div class="col-sm-10">
                                    <img src="{{ asset("uploads/".$district->image)  }}" alt="" width="200px" height="200px">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="thumbImg" class="col-sm-2 control-label">Upload New Photo</label>

                                <div class="col-sm-6">
                                    <input type="file" class="form-control" id="thumbImg" placeholder="Upload file"
                                           name="districtPhoto">
                                </div>
                            </div>

                        </div>

                        <div class="box-footer">
                            <a href="#" class="btn btn-default">Cancel</a>
                            <button type="submit" class="btn btn-info pull-right">Update</button>

                        </div>
                        </form>

                </div>
                <!-- /.box -->
            </div>

        </section>
        <!-- /.content -->

    @endsection

@section('script')
    <script>

        $("#desig").val({{$district->designation_id}});

        $(document).ready(function() {
            const genderOldValue = '{{ $district->district }}';

            if(genderOldValue !== '') {
                $('#dis').val(genderOldValue);
            }
        });


    </script>
@endsection

resources/views/backend/pages/district/list.blade.php
@extends('backend.layouts.app')
@section('title' , 'Central Committee List')

@push('top_scripts')
    <!-- all your includes for Jquery, Bootstrap (optionally), Datatables above -->

    <!-- Now we include the actual plugin -->


    <!-- Finally you define your DataTables table and include a filterDropDown section in the initialisation array -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>

    <script>
        // initialising dt table
        $(document).ready(function() {

            $('#product-list').DataTable({
                // Definition of filter to display
                // format is: idx of column to filter on => text to show as filter name or NULL to use corresponding column header as name
                // also works great with invisible columns e.g. for using unformated data as input
                filterDropDown: {
                    columns: [
                        {
                            idx: 2,
                            title: "District",

                        },
                        {
                            idx: 3,
                            title: "Designation"
                        }
                    ],
                    bootstrap: true
                }
            } );
        } );
    </script>

@endpush
@section('content')

    <div class="box">
        <div class="box-header">
            <div class="col-md-3">
                <h3 class="box-title">District Committee List</h3>
            </div>

            <div class="col-md-6 ">
                <a href="{{ route('backend.district-committee.add') }}" class="btn btn-success">Add District Committee</a>
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body ">
            <table id="product-list" class=" table table-bordered table-striped table-responsive table-hover dataTable" >
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>District</th>
                    <th>Designation</th>
                    <th>Details</th>
                    <th>Email</th>
                    <th>Mobile</th>
                    <th>Image</th>
                    <th>Date</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($committees  as $committee )
                <tr>
                    <td>{{ $committee->id }}</td>

                    <td>{{ $committee->name }}</td>
                    <td>{{ $committee->district }}</td>

                    <td>{{ $committee->designation->title }}</td>

                    <td>{{ $committee->details }}  </td>
                    <td>{{ $committee->email }}</td>
                    <td>{{ $committee->mobile }}</td>
                    <td>
                        <img src="{{ asset("uploads/".$committee->image)  }}" alt="" width="100px" height="100px">

                     </td>

                    <td>{{ date("d-m-Y", strtotime( $committee->created_at))}}</td>

                    <td>
                  {{--      <a href="{{ route('frontend.notice.show',['id'=> $notice->slug]) }}">
                            <i class="fa fa-search-plus fa-lg" style="color:green" aria-hidden="true"></i> </a> --}}&nbsp;
                        <a href="{{ route('backend.district-committee.edit',['id'=> $committee->id]) }}">
                            <i class="fa fa-pencil-square fa-lg" style="color:dodgerblue" aria-hidden="true"></i> </a> &nbsp;
                        <a href=""><i class="fa fa-trash fa-lg deletebtn" data-id="{{ $committee->id }}"
                            data-name="{{ $committee->name }}" data-token="{{ @csrf_token() }}" style="color:red"></i> </a>
                    </td>

                </tr>
                @endforeach

                </tbody>
                <tfoot>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>District</th>
                    <th>Designation</th>
                    <th>Details</th>
                    <th>Email</th>
                    <th>Mobile</th>
                    <th>Image</th>
                    <th>Date</th>
                    <th>Action</th>
                </tfoot>
            </table>
        </div>
        <!-- /.box-body -->
    </div>


@endsection


@push('scripts')


    {{-- DataTable js --}}
    <link rel="stylesheet" href="{{asset('backend/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
    <script src="{{asset('backend/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{asset('backend/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <script>
        $(function () {
            $('#product-list').DataTable();
        });

        $(document).on('click', '.deletebtn', function (e) {
            e.preventDefault();
            var id = $(this).data('id');
            var token = $(this).data('token');

            swal({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'Danger',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        type: "POST",
                        url: "{{route('backend.district-committee.destroy')}}",
                        data: {id:id, _token:token},
                        success: function (data) {
                            if(data.success === true){ // if true (1)
                                setTimeout(function(){  // wait for 5 secs(2)
                                    location.reload();  // then reload the page.(3)
                                }, 100);
                            }
                        }
                    });

                    swal(
                        'Deleted!',
                        'Your file has been deleted.',
                        'success'
                    )
                }
            });

        });

        $(document).ajaxStop(function(){
            window.location.reload();
        });


    </script>
    <script src="{{asset('backend/plugins/filter/filterDropDown.min.js') }}"></script>


@endpush