routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;




//Localization
Route::get('lang/{locale}',function ($locale){
   Session::put('locale',$locale);
   return redirect()->back();
})->name('lang');


Route::name('backend.')
    ->namespace('Backend')
    ->prefix('admin')
    ->middleware('role:admin')
    ->group(function () {

        Route::get('/', 'DashboardController@index')->name('dashboard');

        Route::get('/designation','DesignationController@index' )->name('designation.index');
        Route::post('/designation','DesignationController@store' )->name('designation.store');
        Route::post('/designation-destroy', 'DesignationController@destroy')->name('designation.destroy');




        //central committee
        Route::get('/central-committee','CentralCommitteeController@index' )->name('central-committee.list');
        Route::get('/central-committee-add', 'CentralCommitteeController@create')->name('central-committee.add');
        Route::get('/central-committee-edit/{id}', 'CentralCommitteeController@show')->name('central-committee.edit');
        Route::post('/central-committee-create', 'CentralCommitteeController@store')->name('central-committee.create');
        Route::post('/central-committee-update', 'CentralCommitteeController@update')->name('central-committee.update');
        Route::post('/central-committee-destroy', 'CentralCommitteeController@destroy')->name('central-committee.destroy');



        //district committee
        Route::get('/district-committee','DistrictCommitteeController@index' )->name('district-committee.list');
        Route::get('/district-committee-add', 'DistrictCommitteeController@create')->name('district-committee.add');
        Route::get('/district-committee-edit/{id}', 'DistrictCommitteeController@show')->name('district-committee.edit');
        Route::post('/district-committee-create', 'DistrictCommitteeController@store')->name('district-committee.create');
        Route::post('/district-committee-update', 'DistrictCommitteeController@update')->name('district-committee.update');
        Route::post('/district-committee-destroy', 'DistrictCommitteeController@destroy')->name('district-committee.destroy');


        //district committee
        Route::get('/department-committee','DepartmentCommitteeController@index' )->name('department-committee.list');
        Route::get('/department-committee-add', 'DepartmentCommitteeController@create')->name('department-committee.add');
        Route::get('/department-committee-edit/{id}', 'DepartmentCommitteeController@show')->name('department-committee.edit');
        Route::post('/department-committee-create', 'DepartmentCommitteeController@store')->name('department-committee.create');
        Route::post('/department-committee-update', 'DepartmentCommitteeController@update')->name('department-committee.update');
        Route::post('/department-committee-destroy', 'DepartmentCommitteeController@destroy')->name('department-committee.destroy');



        Route::get('/users', 'DashboardController@userList')->name('user.list');
        Route::get('/users/{id}', 'DashboardController@userShow')->name('user.show');

        //Genereal member
        Route::get('/general-member','GeneralMemberController@index' )->name('general-member.list');
        Route::get('/general-member-edit/{id}', 'GeneralMemberController@show')->name('general-member.edit');
        Route::post('/general-member-create', 'GeneralMemberController@store')->name('general-member.create');
        Route::post('/general-member-update', 'GeneralMemberController@update')->name('general-member.update');
        Route::post('/general-member-destroy', 'GeneralMemberController@destroy')->name('general-member.destroy');


        Route::get('/general-member-successful/{id}', 'GeneralMemberController@successful')->name('general-member.successful');
        Route::get('/general-member-canceled/{id}', 'GeneralMemberController@canceled')->name('general-member.canceled');

        //  notice route
        Route::get('/notice', 'NoticeController@index')->name('notice.list');
        Route::get('/notice-add', 'NoticeController@create')->name('notice.add');
        Route::get('/notice-edit/{id}', 'NoticeController@show')->name('notice.edit');
        // for slug generation
        Route::get('/check_slug', 'NoticeController@check_slug')->name('notice.slug');
        // notice create
        Route::post('/notice-create', 'NoticeController@store')->name('notice.create');
        Route::post('/notice-update', 'NoticeController@update')->name('notice.update');
        Route::post('/notice-destroy', 'NoticeController@destroy')->name('notice.destroy');

    });



Route::name('frontend.')
    ->namespace('Frontend')
    ->group(function (){

        Route::get('/','IndexController@index' )->name('index');

       // Route::get('/general-form', 'CentralCommitteController@index')->name('generalMember.form');
      //  Route::post('/central-form', 'GeneralMemberController@store')->name('generalMember.store');
        Route::get('/central-committee', 'CommitteeController@centralCommittee')->name('centralCommittee.list');

        Route::get('/district-committee', 'CommitteeController@districtCommittee')->name('districtCommittee.list');
        Route::get('/district-committee/{dist}', 'CommitteeController@districtShow')->name('districtCommittee.show');

        Route::get('/department-committee/{dpt}', 'CommitteeController@departmentShow')->name('departmentCommittee.show');


        Route::get('/general-form', 'GeneralMemberController@index')->name('generalMember.form');
        Route::post('/general-form', 'GeneralMemberController@store')->name('generalMember.store');


        Route::get('/dashboard', 'IndexController@dashboard')->name('dashboard');

//        Route::get('/id', 'GeneralMemberController@pdf2')->name('id');

        Route::get('/notices', 'NoticesController@index')->name('notice.list');
        Route::get('/notices/{id}', 'NoticesController@show')->name('notice.show');

        Route::get('/pdf/{id}', 'GeneralMemberController@generatePdf')->name('pdf');

    });

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Notice.php
<?php

namespace App;

use Cocur\Slugify\Slugify;
use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class Notice extends Model
{
    //
    use Sluggable;

    protected $fillable = ['title', 'description', 'file',];
    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    public function customizeSlugEngine(Slugify $engine, $attribute)
    {
      // $engine->activateRuleset('bangla');
        $engine-> addRule('ক', 'ka');
        return $engine;
    }
}

app/Http/Controllers/Backend/NoticeController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Notice;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Cviebrock\EloquentSluggable\Services\SlugService;
use Illuminate\Support\Facades\Storage;

class NoticeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {


        $notice_list = Notice::all();

        return view('backend.pages.notice.list')->with([
                'notices' => $notice_list
        ]);

    }

    public function check_slug(Request $request)
    {
        // New version: to generate unique slugs
        $slug = SlugService::createSlug(Notice::class, 'slug', $request->title);
        return response()->json(['slug' => $slug]);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('backend.pages.notice.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $noticeFile = "";
        $noticefile_upload = $request->file('noticeFile');

        if (isset($noticefile_upload)) {
            if ($noticefile_upload->isValid()) {
                $file_name =
                    uniqid('notice_', true) . str_random(5) . '.' . $noticefile_upload->getClientOriginalExtension();
                $noticeFile = $noticefile_upload->storeAs('notice', $file_name);
            }

        }


        $notice = new Notice();
        $notice->title = $request->noticeTitle;
        $notice->description = $request->noticeDescription;
        $notice->file = $noticeFile;
        $notice->save();
        return redirect()->route('backend.notice.list');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //

        $notice = Notice::where('id',$id)->firstOrFail();


        return view('backend.pages.notice.edit')->with([
            'notice' => $notice
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        //
        $notice = Notice::find($request->id);

        $notice->title = $request->noticeTitle;
        $notice->description = $request->noticeDescription;

        if($request->noticeFile){
            $noticefile_upload = $request->file('noticeFile');

            if (isset($noticefile_upload)) {
                if ($noticefile_upload->isValid()) {
                    $file_name =
                        uniqid('notice_', true) . str_random(5) . '.' . $noticefile_upload->getClientOriginalExtension();
                    $noticeFile = $noticefile_upload->storeAs('notice', $file_name);
                    $notice->file = $noticeFile;
                }

            }
            Storage::delete( $notice->file);


        }

        $notice->save();
        return redirect()->route('backend.notice.list');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        //
        Notice::find($request->id)->delete();
        return redirect()->route('backend.notice.list');
    }
}

app/Http/Controllers/Frontend/NoticesController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Notice;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class NoticesController extends Controller
{

    public function index() {

        $notices = Notice::orderBy('created_at', 'desc')->paginate(30);

        return view('frontend.pages.noticeList')->with([
            'notices' => $notices
        ]);
    }

    public function show($id)
    {
        $notice = Notice::find($id)->get();

        return view('frontend.pages.singleNotice')->with([
            'notice' => $notice
        ]);
    }




}

resources/views/backend/pages/notice/add.blade.php
@extends('backend.layouts.app')
@section('title' , 'Notice')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            New Notice
            <small>Create a new notice</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Admin</a></li>
            <li class="active">New Notice</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content container-fluid">

        <div class="product">
            <!-- Horizontal Form -->
            <div class="box box-info">
                <!-- form start -->
                <form accept-charset="UTF-8" class="form-horizontal" action="{{ route('backend.notice.create') }}" method="post"
                      enctype="multipart/form-data">
                    @csrf
                    <div class="box-body">

                        <div class="form-group">
                            <label for="inputTitle" class="col-sm-2 control-label">Title</label>

                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="inputTitle" name="noticeTitle" placeholder="Title" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputNoticeSlug" class="col-sm-2 control-label">Slug</label>

                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="inputNoticeSlug" name="noticeSlug"
                                       placeholder="Slug (auto generate)" required>
                            </div>
                        </div>


                        <div class="form-group">
                            <label for="inputDescription" class="col-sm-2 control-label">Description</label>

                            <div class="col-sm-10">
                                <textarea class="form-control" id="inputDescription" name="noticeDescription"
                                          placeholder="Description"></textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="thumbImg" class="col-sm-2 control-label">Upload File</label>

                            <div class="col-sm-6">
                                <input type="file" class="form-control" id="thumbImg" placeholder="Upload file"
                                       name="noticeFile">
                            </div>
                        </div>

                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <a href="#" class="btn btn-default">Cancel</a>
                        <button type="submit" class="btn btn-info pull-right">Create</button>
                    </div>
                    <!-- /.box-footer -->
                </form>
            </div>
            <!-- /.box -->
        </div>

    </section>
    <!-- /.content -->

@endsection

@section('script')
    <script>
        $('#inputTitle').on('input',function (e) {
                 console.log($(this).val());
            $.get('{{ route('backend.notice.slug') }}',
                { 'title' : $(this).val() },
                function (data) {
                    $('#inputNoticeSlug').val(data.slug);
                }
            );

        });

    $(function () {
    // Replace the <textarea id="editor1"> with a CKEditor
        // instance, using default configuration.
        CKEDITOR.replace('inputDescription')
        //bootstrap WYSIHTML5 - text editor
        $('.textarea').wysihtml5()
    })
    </script>
@endsection

resources/views/backend/pages/notice/edit.blade.php
@extends('backend.layouts.app')
@section('title' , 'Notice Edit')

@section('content')

        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Update Product info
                <small>{{ $notice->name }} </small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ route('backend.dashboard') }}"><i class="fa fa-dashboard"></i> Admin</a></li>
                <li><a href=" {{ route('backend.notice.list') }}"><i class="fa fa-shopping-cart"></i> Notice</a></li>
                <li class="active">Edit Notice</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content container-fluid">

            <div class="product">
                <!-- Horizontal Form -->
                <div class="box box-info">
                    <!-- form start -->
                    <form accept-charset="UTF-8" class="form-horizontal" action="{{ route('backend.notice.update') }}" method="post"
                          enctype="multipart/form-data">
                        @csrf
                        <input type="hidden" class="form-control"  name="id" value="{{ $notice->id }}" >

                        <div class="box-body">

                            <div class="form-group">
                                <label for="inputTitle" class="col-sm-2 control-label">Title</label>

                                <div class="col-sm-10">
                                    <input type="text" class="form-control" id="inputTitle" name="noticeTitle"
                                           placeholder="Title" value="{{ $notice->title }}" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputNoticeSlug" class="col-sm-2 control-label">Slug</label>

                                <div class="col-sm-10">
                                    <input type="text" class="form-control" id="inputNoticeSlug" name="noticeSlug"
                                           value="{{ $notice->slug }}"    placeholder="Slug (auto generate)" required>
                                </div>
                            </div>


                            <div class="form-group">
                                <label for="inputDescription" class="col-sm-2 control-label">Description</label>

                                <div class="col-sm-10">
                                <textarea class="form-control" id="inputDescription" name="noticeDescription"
                                          placeholder="Description">{{ $notice->description }}</textarea>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="thumbImg" class="col-sm-2 control-label">File </label>

                                <div class="col-sm-6">
{{--                                    <iframe src="https://docs.google.com/gview?url={{asset("uploads/".$notice->file)}}" style="" width="100%" height="500px" allowfullscreen="" webkitallowfullscreen=""></iframe>--}}

{{--                                        <iframe src="http://docs.google.com/gview? url={{asset("uploads/".$notice->file)}}"--}}
{{--                                            style="width:600px; height:500px;" frameborder="0">--}}
{{--                                    </iframe>--}}
                                {{--    <embed name="plugin" src="{{asset("uploads/".$notice->file)}}" type="application/pdf">--}}
                                  {{--  <object type="application/pdf" width="400" height="500" data="{{asset("uploads/".$notice->file)}}"></object>--}}
                                </div>
                            </div>


                            <div class="form-group">
                                <label for="thumbImg" class="col-sm-2 control-label">Upload File </label>

                                <div class="col-sm-6">
                                    <input type="file" class="form-control" id="thumbImg" placeholder="Upload file"

                                           name="noticeFile">
                                </div>
                            </div>


                        </div> <div class="box-footer">
                            <a href="#" class="btn btn-default">Cancel</a>
                            <button type="submit" class="btn btn-info pull-right">Update</button>

                        </div>
                        </form>

                </div>
                <!-- /.box -->
            </div>

        </section>
        <!-- /.content -->

    @endsection

@section('script')
    <script>
        $('#inputTitle').on('input',function (e) {
            console.log($(this).val());
            $.get('{{ route('backend.notice.slug') }}',
                { 'title' : $(this).val() },
                function (data) {
                    $('#inputNoticeSlug').val(data.slug);
                }
            );

        });

        $(function () {
            // Replace the <textarea id="editor1"> with a CKEditor
            // instance, using default configuration.
            CKEDITOR.replace('inputDescription')
            //bootstrap WYSIHTML5 - text editor
            $('.textarea').wysihtml5()
        })
    </script>
@endsection

resources/views/backend/pages/notice/list.blade.php
@extends('backend.layouts.app')
@section('title' , 'Notice List')

@section('content')

    <div class="box">
        <div class="box-header">
            <div class="col-md-3">
                <h3 class="box-title">Notice list</h3>
            </div>

            <div class="col-md-6 ">
                <a href="{{ route('backend.notice.add') }}" class="btn btn-success">Add Notice</a>
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table id="product-list" class="table table-bordered table-striped table-responsive table-hover" >
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Title</th>
                    <th>Slug</th>
                    <th>Description</th>
                    <th>File</th>
                    <th>Date</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($notices  as $notice )
                <tr>
                    <td>{{ $notice->id }}</td>

                    <td> {{ str_limit($notice->title, $limit= 20, $end = ' ....') }}</td>

                    <td>{{ $notice->slug }}</td>
                    <td>{!!  str_limit($notice->description, $limit= 20, $end = ' ....') !!}   </td>
                    <td>
                        @if ( $notice->file)
                           Yes
                        @else
                            No
                        @endif



                     </td>
                    <td>{{ date("d-m-Y", strtotime( $notice->created_at))}}</td>

                    <td>
                  {{--      <a href="{{ route('frontend.notice.show',['id'=> $notice->slug]) }}">
                            <i class="fa fa-search-plus fa-lg" style="color:green" aria-hidden="true"></i> </a> --}}&nbsp;
                        <a href="{{ route('backend.notice.edit',['id'=> $notice->id]) }}">
                            <i class="fa fa-pencil-square fa-lg" style="color:dodgerblue" aria-hidden="true"></i> </a> &nbsp;
                        <a href=""><i class="fa fa-trash fa-lg deletebtn" data-id="{{ $notice->id }}"
                            data-name="{{ $notice->name }}" data-token="{{ @csrf_token() }}" style="color:red"></i> </a>
                    </td>

                </tr>
                @endforeach

                </tbody>
                <tfoot>
                <tr>
                    <th>Id</th>
                    <th>Title</th>
                    <th>Slug</th>
                    <th>Description</th>
                    <th>File</th>
                    <th>Date</th>
                    <th>Action</th>
                </tr>
                </tfoot>
            </table>
        </div>
        <!-- /.box-body -->
    </div>


@endsection


@push('scripts')


    {{-- DataTable js --}}
    <link rel="stylesheet" href="{{asset('backend/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
    <script src="{{asset('backend/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{asset('backend/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <script>
        $(function () {
            $('#product-list').DataTable();
        });

        $(document).on('click', '.deletebtn', function (e) {
            e.preventDefault();
            var id = $(this).data('id');
            var token = $(this).data('token');

            swal({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'Danger',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        type: "POST",
                        url: "{{route('backend.notice.destroy')}}",
                        data: {id:id, _token:token},
                        success: function (data) {
                            if(data.success === true){ // if true (1)
                                setTimeout(function(){  // wait for 5 secs(2)
                                    location.reload();  // then reload the page.(3)
                                }, 100);
                            }
                        }
                    });

                    swal(
                        'Deleted!',
                        'Your file has been deleted.',
                        'success'
                    )
                }
            });

        });

        $(document).ajaxStop(function(){
            window.location.reload();
        });


    </script>
@endpush